definitions:
  apperror.Error:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  domain.Balance:
    properties:
      balance:
        type: number
      user_id:
        type: string
    type: object
  domain.Transaction:
    properties:
      amount:
        type: number
      comment:
        type: string
      created_at:
        type: string
      id:
        type: string
      payee_id:
        type: string
      payer_id:
        type: string
      type:
        type: string
    type: object
  dto.Credit:
    properties:
      amount:
        example: 100
        type: number
      comment:
        example: took it from an ATM
        type: string
      user_id:
        example: bcf4b5f7-8f73-4205-82e6-cf20e898a98a
        type: string
    type: object
  dto.Debet:
    properties:
      amount:
        example: 100
        type: number
      comment:
        example: salary
        type: string
      user_id:
        example: bcf4b5f7-8f73-4205-82e6-cf20e898a98a
        type: string
    type: object
  dto.Transfer:
    properties:
      amount:
        example: 100
        type: number
      comment:
        example: paid the debt
        type: string
      payee_id:
        example: a39c71f8-6d1b-466c-8367-ebd86764268b
        type: string
      payer_id:
        example: bcf4b5f7-8f73-4205-82e6-cf20e898a98a
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/balance:
    get:
      parameters:
      - description: user id
        format: uuid
        in: query
        name: user_id
        required: true
        type: string
      - description: currency
        format: string
        in: query
        name: currency
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Balance'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Retrieves balance based on given user ID
  /api/v1/balance/credit:
    post:
      parameters:
      - description: credit params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.Credit'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Transaction'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Withdraws money from the balance by user id
  /api/v1/balance/debet:
    post:
      parameters:
      - description: debet params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.Debet'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Balance'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Deposits money to the balance by user id
  /api/v1/balance/transaction:
    get:
      parameters:
      - description: user id
        format: uuid
        in: query
        name: user_id
        required: true
        type: string
      - description: sort
        enum:
        - amount
        - created_at
        in: query
        name: sort
        type: string
      - description: order
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      - description: count
        format: int
        in: query
        name: count
        type: integer
      - description: offset
        format: int
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Transaction'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Retrieves transactions based on given user ID
  /api/v1/balance/transfer:
    post:
      parameters:
      - description: transfer params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.Transfer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Transfer money from payer id to payee id
swagger: "2.0"
